name: GodLevelMusic
favicon: null
layout_spectrum: 0.1258517950773239
typography_spectrum: 0.7304058470763266
title: 'Apollo & King Zeus'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.49643305595964193
  lightness: 0.4588638972491026
  saturation: 0.9293150699231774
  rhythmicContrast: 0.3370258442591876
purpose: []
